### ISSUE TITLE
Add requirement for Python > 3.10

### ISSUE THREAD

**Issue by quinnwai** [gks-anvil/vrs_anvil_toolkit#14]
The latest version of seqrepo (>0.65) requires python >3.10, so to allow for recent changes making seqrepo thread-safe, we need to change the venv to reflect this

**Comment by bwalsh** [comment]
@quinnwai  See https://github.com/ohsu-comp-bio/vrs-python-testing/blob/2d4da85eac9eb21ac7956ba9fb6a77a13917186b/setup.py#L100

If satisfactory, please close this issue

**Comment by quinnwai** [comment]
noted, thanks! Closing issue
