### ISSUE TITLE
research/multithreading-vs-multiprocessing performance

### ISSUE THREAD

**Issue by quinnwai** [gks-anvil/vrs_anvil_toolkit#15]
Compare the performance of multithreading vs multiprocessing in terms of performance. Describe the results here

**Comment by bwalsh** [comment]
@quinnwai not sure we will get to this?

**Comment by quinnwai** [comment]
agreed, doesn't have to be priority. I think the more important question will be contrasting our methods to vrs-python

**Comment by quinnwai** [comment]
closing, as multiprocessing has been implemented in the form of per-process VCF file processing
