### ISSUE TITLE
feature/query-metakb-cache

### ISSUE THREAD

**Issue by bwalsh** [gks-anvil/vrs_anvil_toolkit#37]
See 
* setup metakb cache in cache/ dir read from manifest
* query metakb cache [here](https://github.com/ohsu-comp-bio/vrs-python-testing/blob/d088ef23fab9c73fcba5d84c646179be9f551ba8/vrs_anvil/annotator.py#L88-L90)
* add metakb hit/miss counters to metrics

**Comment by quinnwai** [comment]
**Goal**
Given a single VCF (for now), be able to get any VRS IDs that are associated with metakb results.

Specifically
- [x] Have significantly faster gains when loading cached VRS IDs (when cache set to true) (4x speed up)
- [x] Store the relevant gnomad or VRS IDs associated with the metakb hit
- [x] Records statistics like metakb hits to metrics
- [x] Add a unit test making sure that some expected IDs fill the cache

**Analysis**
Currently, every call to `vrs_anvil annotate` creates a work/metrics file that stores aggregated data, including hits to metakb, but there's no way to store more fine-grained data like VRS IDs or metakb hits. Also, gnomad to vrs caching exists but no timing has been established for it (ie no feasibility claims have been made for it). The question is how to store the results of metakb. Specifically, the results dict looks like this:

```
{'parameters': {'fmt': 'gnomad', 'var': 'chr1-100968-C-T'}, 'file': PosixPath('work/1kGP.chr1.head.100.000.vcf'), 'line': 1382, 'result': Allele(id='ga4gh:VA.XKbPyce0zVYVZ5oBZhZSLz_SGFd4aE2R', label=None, description=None, extensions=None, type='Allele', digest='XKbPyce0zVYVZ5oBZhZSLz_SGFd4aE2R', expressions=None, location=SequenceLocation(id='ga4gh:SL.Qw3Hx9Q5tyT0C_y4BU_GLoMPil0KXePT', label=None, description=None, extensions=None, type='SequenceLocation', digest='Qw3Hx9Q5tyT0C_y4BU_GLoMPil0KXePT', sequenceReference=SequenceReference(id=None, label=None, description=None, extensions=None, type='SequenceReference', refgetAccession='SQ.Ya6Rs7DHhDeg7YaOSg1EoNi3U_nQ9SvO', residueAlphabet=None), start=100967, end=100968), state=LiteralSequenceExpression(id=None, label=None, description=None, extensions=None, type='LiteralSequenceExpression', sequence=SequenceString(root='T')))}
```

Storing just the VRS ID gives us no way to refer back to the original file (needed for the 1000g use case). Storing just the filename and line number doesn't exactly work either, as both of those can be easily changed. To most quickly be able to access one variant in a single VCF using tools like `pysam`, we need the coordinate info, so storing vrs_id -> gnomad expression should be sufficient
