### ISSUE TITLE
gather data, prepare presentation

### ISSUE THREAD

**Issue by quinnwai** [gks-anvil/vrs_anvil_toolkit#39]
![IMG_2670](https://github.com/ohsu-comp-bio/vrs-python-testing/assets/54592956/d2b62cfa-0c7b-4efd-918c-c399a45d6cfe)

**Comment by bwalsh** [comment]
Select files for chr1: patient 1-10
* Complete processing, collecting metrics: Save & maintain metrics between runs
* After runs, observe disk utilization, if we run out of diskspace, we may need to implement #36 
* Write issues/fix bugs along the way.
* Save & maintain cache between runs
* Use metrics to generate figures.

Repeat for expanded datasets to chr2,3 ...
Repeat for expanded datasets to p11, 12 ...

Tech note: document work, architecture digram, document bugs, limitations
  * as part of processing, and documenting limitations what workarounds are necessary &/or useful
  * [`nohup`](https://www.digitalocean.com/community/tutorials/nohup-command-in-linux) is your friend
  * terra workflow (as / if needed)


**note** ⚠️ use notebooks for figure creation & exploratory data analysis, not for running "jobs"
* notebooks are notoriously non reproducible.
* tests, and "cleanroom" scripts are reproducible

**Comment by quinnwai** [comment]
**Structure of Presentation**
![IMG_2649](https://github.com/ohsu-comp-bio/vrs-python-testing/assets/54592956/79419791-a2cd-4ae1-8d76-825bfa345a7c)

**Info to Add**
- 5x performance decrease in Terra vs raw GCP, matched hardware (8 CPUs, memory, etc)

**Comment by quinnwai** [comment]
presenting today 💯
