### ISSUE TITLE
bug/logger-not-logging

### ISSUE THREAD

**Issue by quinnwai** [gks-anvil/vrs_anvil_toolkit#54]
All calls to logger files are not being displayed when running the CLI... why?

**Comment by quinnwai** [comment]
I think the logs are supposed to write to a file, so this might be okay. Check with @bwalsh

**Comment by bwalsh** [comment]
Yes the log file setup is in the cli.py package.  A recent change was the "log to file" feature only happens in the 'annotate' command. ie the 'ps' command does not create a log file

**Comment by bwalsh** [comment]
@quinnwai close if appropriate
