### ISSUE TITLE
Make setup script idempotent

### ISSUE THREAD

**Issue by bwalsh** [gks-anvil/vrs_anvil_toolkit#59]
ie. what if the user (needs to) run it twice?

Perhaps check if venv already exists?
https://github.com/ohsu-comp-bio/vrs-python-testing/blob/development/scripts/setup.sh#L3-L6

Are there other issues if setup run twice?

**Comment by quinnwai** [comment]
To my understanding, the script still works if I am rerunning the setup, here's the logs

> $ bash scripts/setup.sh 
Requirement already satisfied: ga4gh.vrs==2.0.0a5 in ./venv/lib/python3.12/site-packages (from ga4gh.vrs[extras]==2.0.0a5->-r requirements.txt (line 1)) (2.0.0a5)
...
Requirement already satisfied: asttokens>=2.1.0 in ./venv/lib/python3.12/site-packages (from stack-data->ipython~=8.4->biocommons.seqrepo->-r requirements.txt (line 3)) (2.4.1)
Requirement already satisfied: pure-eval in ./venv/lib/python3.12/site-packages (from stack-data->ipython~=8.4->biocommons.seqrepo->-r requirements.txt (line 3)) (0.2.2)
mkdir: /Users/wongq/seqrepo: File exists
WARNING:biocommons.seqrepo.cli:2024-02-20: instance already exists; skipping
bcftools already installed, not installing

let me know if I'm missing something

**Comment by quinnwai** [comment]
add documentation about adding postgresql for Linux (psql) or otherwise

also add to setup script python < 3.12 setup:
```
if running-on-terra and python-version < 3.12:
  install pyenv
  install 3.12 on pyenv
  update .bashrc
# continue with setup
```

```
# install pyenv
curl https://pyenv.run/ | bash

# setup your path
cat ~/.bashrc
>>> export PYENV_ROOT="$HOME/.pyenv"
>>> [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"

source  ~/.bashrc

# confirm installation ok
pyenv versions

# install 3.12
pyenv install 3.12

# update 3.12 for our project
cd  /home/jupyter/vrs-python-testing
pyenv local 3.12

# re-create vent
rm -r vent

# setup venv …. pip install ….
```
