### ISSUE TITLE
feature/metrics-as-CohortAlleleFrequency

### ISSUE THREAD

**Issue by bwalsh** [gks-anvil/vrs_anvil_toolkit#65]
As a vrs_anvil user, I need to be able to consume results in an agreed upon form.

https://github.com/ga4gh/va-spec/blob/1.x/schema/va-spec/profiles/caf/json/CohortAlleleFrequency

**Comment by bwalsh** [comment]
Also here:
https://github.com/broadinstitute/gnomad_methods/blob/main/gnomad/utils/annotations.py
https://github.com/broadinstitute/gnomad_methods/blob/main/gnomad/utils/annotations.py#L2546

**Comment by bwalsh** [comment]
https://github.com/ga4gh/va-spec/blob/bbd1c128818ce4093ef222fb0c8c8f211cdd64a8/Modeling/Population%20Frequency/gnomad_study_result_examples_v6_20230126.yml

**Comment by quinnwai** [comment]
Note: this has been implemented in the `1000g-figure.py` script to reproduce the 1000G analysis on Terra, but we may want to formalize this into the package.

**Comment by quinnwai** [comment]
supersetted by #94
