### ISSUE TITLE
feature/populate-identifier

### ISSUE THREAD

**Issue by bwalsh** [gks-anvil/vrs_anvil_toolkit#66]
As a informatician, when I have a "hit", I need to know what line it came from.

What is the best way to populate [identifier](https://github.com/ohsu-comp-bio/vrs-python-testing/blob/feature/better-threaded-translator/vrs_anvil/translator.py#L57)?
https://github.com/ohsu-comp-bio/vrs-python-testing/blob/feature/better-threaded-translator/vrs_anvil/annotator.py#L78

**Comment by bwalsh** [comment]
The translator accepts a VCFItem.  The item.fmt and item.var are passed to vrs-python.  The result (vrs-python.Allele) is added the item.  The entire item, including item.file_name item.line_number and **item.identifier** are returned to the caller.

* Is there an identifier value that we can use to denote specimen(s) ?
* Should we be logging the item.file_name item.line_number and **item.identifier**  fields to metrics?

**Comment by quinnwai** [comment]
May be helpful, here is the most up to date version returning samples/specimen for a given variant row in VCF. https://github.com/ohsu-comp-bio/vrs-python-testing/blob/100fe26f21ba16f18d1df41990cbcd94733de975/scripts/1000g-sample-stats.py/#L67-L88

**Comment by bwalsh** [comment]
closing for see #44
