### ISSUE TITLE
bug/scatter-creates-zombies-without-nohup

### ISSUE THREAD

**Issue by quinnwai** [gks-anvil/vrs_anvil_toolkit#70]
When doing `vrs_anvil annotate --scatter` in Python, killing the process (ctrl c) kills the parent but not the children. Fix this so that we don't get zombie processes for the children as well.

**Comment by bwalsh** [comment]
<img width="767" alt="image" src="https://github.com/ohsu-comp-bio/vrs-python-testing/assets/47808/1898ed93-d1c5-4ba7-9925-d2406ee5adf6">
