### ISSUE TITLE
feature/access-output-files-by-timestamp

### ISSUE THREAD

**Issue by quinnwai** [gks-anvil/vrs_anvil_toolkit#71]
timestamps are not the same sometimes between manifest and the metrics/log file, even though the same timestamp string is being used.

<img width="924" alt="image" src="https://github.com/ohsu-comp-bio/vrs-python-testing/assets/54592956/b3672ce7-d7f1-404e-92bb-61914479d252">

**Comment by bwalsh** [comment]
The timestamps for manifest and log/metrics are separate processes therefore separate strings.

**Comment by bwalsh** [comment]
A fix would probably be:
* add optional timestamp to manifest
* if set use it

**Comment by quinnwai** [comment]
Initial motivation: as an analyst, I want to be able to get all the metrics for a given run from a single timestamp. For example, by targeting the manifest files' timestamp, I should be able to retrieve all metrics/logs for a guveb run a without needing matching timestamps between the manifest and metrics. 

Changing to feature to make, not bug
